#!/bin/bash
#
# Lemonbar script
#

font="xft:{{font}}:size={{font_size}}"
glyphs="{{icon_font}}-{{font_size}}"

fg="{{ fg }}"
bg="{{ bg }}"
light="{{ light }}"

getTime(){
  echo "%{F$light} %{F$fg}$(date +"%I:%M")"
}

getCpu() {
  echo "%{F$light} %{F$fg}$(echo $(ps -A -o pcpu | tail -n+2 | paste -sd+ | bc) / 2 | bc)%"
}

getBattery() {
  icon=""
  if [[ $(cat /sys/class/power_supply/BAT0/status) = "Charging" ]]; then
    icon=""
  fi
  echo "%{F$light}"$icon%{F$fg} $(cat /sys/class/power_supply/BAT0/capacity)
}

getDesktop(){
  for i in $(bspc query -D); do
    if [ $i = $(bspc query -D -d) ]; then
      echo %{F$light}
    else
      echo %{F$fg}
    fi
  done
}

killall lemonbar

while true; do
  echo %{l} "  " $(getDesktop)%{r} $(getBattery) " " $(getCpu) " " $(getTime)"   "   
  sleep 1
done | lemonbar -g "1400x80+1220+0" -B $bg -o 0 -f $font -o -3 -f $glyphs | sh &
