#!/bin/zsh
#
# Bspwm configuration
#

# =====================
# Initialition
# =====================

~/bin/bar.sh
compton --vsync opengl --paint-on-overlay &
hsetroot -solid "{{ bg }}"

xinput set-prop 15 274 1
xinput set-prop 15 295 1

# =====================
# Config
# =====================

bspc config focused_border_color "{{ blu }}"
bspc config normal_border_color "{{ bg }}"
bspc config presel_feedback_color "{{ grn }}"

bspc config border_width        10
bspc config window_gap          90
bspc config top_padding         50

bspc config split_ratio          0.5

bspc config paddingless_monocle  true
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       true

bspc monitor -d 1 2 3 4 5 6
