[files]
xresources = "/home/matt/.Xresources"
termite = "/home/matt/.config/termite/config"
bar = "/home/matt/bin/bar.sh"
bspwmrc = "/home/matt/.config/bspwm/bspwmrc"
sxhkdrc = "/home/matt/.config/sxhkd/sxhkdrc"
dunstrc = "/home/matt/.config/dunst/dunstrc"

[default]
font = "DejaVuSansMono"
icon_font = "MaterialIcons"
font_size = "26"
font_size_small = "24"
bg_command = "hsetroot -fill ~/img/bg.jpg"
bg = "#181818"
fg = "#d8d8d8"
light = "#a1b56c"
